id: IssueManagement.ResolveStale
name: GitOps.PullRequestIssueManagement
description: Other issue management rules for closing stale and waiting on author requests
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - description: Close if marked as Waiting on Author and no activity in 7 days
      frequencies:
      - hourly:
          hour: 12
      filters:
      - isOpen
      - isIssue
      - hasLabel:
          label: Waiting on Author
      - noActivitySince:
          days: 7
      actions:
      - addReply:
          reply: This issue has been marked as "Waiting on Author" and has not had any activity for **7 day**. It has been closed for housekeeping purposes.
      - closeIssue
    - description: Label as Resolution-No Activity if not labeled with KeepOpen and no activity in 6 months
      frequencies:
      - hourly:
          hour: 24
      filters:
      - isIssue
      - isOpen
      - isNotLabeledWith:
          label: KeepOpen
      - isNotLabeledWith:
          label: Resolution-No Activity
      - noActivitySince:
          days: 180
      actions:
      - addReply:
          reply: This issue has not had any activity in 6 months, if this is a bug please try to reproduce on the latest version of PowerShell and reopen a new issue and reference this issue if this is still a blocker for you. 
      - addLabel:
            label: Resolution-No Activity
    eventResponder:
    - description: Reopen issues with no activity if its the author who has commented
    - description: If new issue comment is author then remove waiting on author
      if:
      - payloadType: Issue_Comment
      - isActivitySender:
          issueAuthor: True
      - hasLabel:
          label: Waiting on Author
      then:
      - removeLabel:
          label: Waiting on Author
    - description: Remove Stale label if issue comment 
      if:
      - payloadType: Issue_Comment
      - hasLabel:
          label: Stale
      then:
      - removeLabel:
          label: Stale
    - description: Remove Needs-Triage label if issue is closed
      if:
      - payloadType: Issues
      - isAction:
          action: Closed
      then:
      - removeLabel:
          label: Needs-Triage
    - description: Remove Waiting on Author label if issue comment is from author
      if:
      - payloadType: Issue_Comment
      - isActivitySender:
          issueAuthor: True
      - hasLabel:
          label: Waiting on Author
      then:
      - removeLabel:
          label: Waiting on Author
onFailure:
onSuccess:
