language: cpp

os:
  - linux
  - osx
sudo: required
dist: trusty
osx_image: xcode8

cache:
  directories:
    - $HOME/.dotnet
    - $HOME/.nuget

addons:
  artifacts:
    s3_region: "us-west-2"
    paths: $(ls powershell*{deb,pkg} | tr "\n" ":")

# submodules must be init manually because this will fail authentication
git:
  submodules: false

before_install:
  # pass the build early if only ignored files where touched
  - git diff --name-only "${TRAVIS_COMMIT_RANGE/.../..}" | grep -q -v -f tools/travis_ignore || exit 0
  # use SSH to init private submodules
  - git config --global url.git@github.com:.insteadOf https://github.com/
  - git submodule update --init

install:
  - (cd tools && ./download.sh)

script: ./tools/travis.sh
