# version is set in tools\appveyor.psm1 - Invoke-AppVeyorInstall
environment:
  POWERSHELL_TELEMETRY_OPTOUT: 1
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    Purpose: Testing
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    Purpose: Packaging

# cache version - netcoreapp.2.1-sdk.2.1.300-rc1
cache:
  - '%LocalAppData%\Microsoft\dotnet -> appveyor.yml'
  - '%HOMEDRIVE%%HOMEPATH%\.nuget\packages -> appveyor.yml'

nuget:
  project_feed: true

install:
  - git submodule update --init
  - ps: Import-Module .\tools\Appveyor.psm1
  - ps: Invoke-AppveyorInstall

build_script:
  - ps: if ($env:Purpose -eq 'Testing'){ Invoke-AppveyorBuild }

test_script:
  - ps: if ($env:Purpose -eq 'Testing'){ Invoke-AppveyorTest }

after_test:
  - ps: if ($env:Purpose -eq 'Testing'){ Invoke-AppVeyorAfterTest }

# Run the finish command and delete files which should not be in the cache
on_finish:
  - ps: if ($env:Packaging -eq 'Packaging'){ Invoke-AppveyorFinish }
  - ps: Invoke-AppVeyorCleanCache
