# version is set in tools\appveyor.psm1 - Invoke-AppVeyorInstall
environment:
  POWERSHELL_TELEMETRY_OPTOUT: 1
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    Purpose: BuildingAndPackaging
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    Purpose: BuildingAndTesting

# Stop all jobs in the matrix if any one them fail
matrix:
  fast_finish: true

cache:
  - '%HOMEDRIVE%%HOMEPATH%\.nuget\packages -> appveyor.yml'

nuget:
  project_feed: true

install:
  - git submodule update --init
  - ps: Import-Module .\tools\Appveyor.psm1
  - ps: Invoke-AppveyorInstall

build_script:
  - ps: if ($env:Purpose -eq 'BuildingAndTesting'){ Invoke-AppveyorBuild }

test_script:
  - ps: if ($env:Purpose -eq 'BuildingAndTesting'){ Invoke-AppveyorTest }

after_test:
  - ps: if ($env:Purpose -eq 'BuildingAndTesting'){ Invoke-AppVeyorAfterTest }

# Run the finish command and delete files which should not be in the cache
on_finish:
  - ps: if ($env:Purpose -eq 'BuildingAndPackaging'){ Invoke-AppveyorFinish }
