name: PR-$(System.PullRequest.PullRequestNumber)-$(Date:yyyyMMdd)$(Rev:.rr)
trigger:
  branches:
    include:
    - master
    - release*
  paths:
    exclude:
    - /src/*

pr:
  branches:
    include:
    - master
    - release*
  paths:
    exclude:
    - /src/*

resources:
- repo: self
  clean: true
phases:
- phase: Linux_CI

  queue:
    name: Hosted Ubuntu 1604
  steps:
  - powershell: |
      Get-ChildItem -Path env:
    displayName: Capture environment
    condition: succeededOrFailed()
  - bash: |
      npm install -g markdown-link-check@3.7.2
    displayName: Install needed library
    condition: succeededOrFailed()
  - powershell:  Write-Host "##vso[build.updatebuildnumber]$env:BUILD_SOURCEBRANCHNAME-$env:BUILD_SOURCEVERSION-$((get-date).ToString("yyyyMMddhhmmss"))"
    displayName: Set Build Name for Non-PR
    condition: ne(variables['Build.Reason'], 'PullRequest')

  - bash: |
      find . -name \*.md -exec markdown-link-check {} \;
    displayName: Test Links
    condition: succeededOrFailed()
