name: PR-$(System.PullRequest.PullRequestNumber)-$(Date:yyyyMMdd)$(Rev:.rr)
trigger:
  # Batch merge builds together while a merge build is running
  batch: true
  branches:
    include:
    - master
    - release*
    - feature*
  paths:
    include:
    - '*'
    exclude:
    - .vsts-ci/misc-analysis.yml
    - .github/ISSUE_TEMPLATE/*
    - .dependabot/config.yml
    - test/perf/*
pr:
  branches:
    include:
    - master
    - release*
    - feature*
  paths:
    include:
    - '*'
    exclude:
    - .dependabot/config.yml
    - .github/ISSUE_TEMPLATE/*
    - .vsts-ci/misc-analysis.yml
    - .vsts-ci/windows.yml
    - .vsts-ci/windows/*
    - tools/cgmanifest.json
    - LICENSE.txt
    - test/common/markdown/*
    - test/perf/*
    - tools/releaseBuild/*
    - tools/releaseBuild/azureDevOps/templates/*
    - README.md
    - .spelling

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1
  # Avoid expensive initialization of dotnet cli, see: https://donovanbrown.com/post/Stop-wasting-time-during-NET-Core-builds
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  __SuppressAnsiEscapeSequences: 1

resources:
  repositories:
    - repository: Docker
      type: github
      endpoint: PowerShell
      name: PowerShell/PowerShell-Docker
      ref: master

stages:
- stage: BuildLinuxStage
  displayName: Build for Linux
  jobs:
  - template: templates/ci-build.yml
    parameters:
      pool: ubuntu-20.04
      jobName: linux_build
      displayName: linux Build

- stage: TestUbuntu
  displayName: Test for Ubuntu
  dependsOn: [BuildLinuxStage]
  jobs:
  - template: templates/nix-test.yml
    parameters:
      name: Ubuntu
      pool: ubuntu-20.04
      purpose: UnelevatedPesterTests
      tagSet: CI

  - template: templates/nix-test.yml
    parameters:
      name: Ubuntu
      pool: ubuntu-20.04
      purpose: ElevatedPesterTests
      tagSet: CI

  - template: templates/nix-test.yml
    parameters:
      name: Ubuntu
      pool: ubuntu-20.04
      purpose: UnelevatedPesterTests
      tagSet: Others

  - template: templates/nix-test.yml
    parameters:
      name: Ubuntu
      pool: ubuntu-20.04
      purpose: ElevatedPesterTests
      tagSet: Others

  - template: templates/verify-xunit.yml
    parameters:
      pool: ubuntu-20.04

- stage: TestContainer
  displayName: Test in a container
  dependsOn: [BuildLinuxStage]
  jobs:
  - job: getContainerJob
    displayName: Choose a container
    pool:
      vmImage: ubuntu-20.04
    steps:
    - checkout: self
      clean: true

    - checkout: Docker
      clean: true

    - pwsh: |
        $buildId = $env:BUILD_BUILDID
        Write-Verbose "Fall back seed: $buildId" -Verbose
        # For PRs set the seed to the PR number so that the image is always the same
        $seed = $env:SYSTEM_PULLREQUEST_PULLREQUESTID
        if(!$seed) {
          # for non-PRs use the integer identifier of the build as the seed.
          $seed = $buildId
        }
        Write-Verbose "Seed: $seed" -Verbose

        # Get the latest image matrix JSON for preview
        $matrix = ./PowerShell-Docker/build.ps1 -GenerateMatrixJson -FullJson -Channel preview | ConvertFrom-Json

        # Filter out containers that won't run on AzDevOps Linux host as an agent
        # Windows, nano server, alpine, and any ARM image
        $linuxImages = $matrix.preview |
          Where-Object {$_.osversion -notmatch 'windows|nano|alpine|arm'} |
          Select-Object JobName, Taglist |
          Sort-Object -property JobName

        # Force mariner for now
        $marinerImage = $linuxImages | where-object {$_.JobName -like 'mariner*'}

        # Use the selected seed to pick a container
        $index = Get-Random -Minimum 0 -Maximum $marinerImage.Count -SetSeed $seed
        $selectedImage = $marinerImage[$index]

        # Filter to the first test-deps compatible tag
        $tag = $selectedImage.Taglist -split ';' | Where-Object {$_ -match 'preview-\D+'} | Select-Object -First 1

        # Calculate the container name
        $containerName = "mcr.microsoft.com/powershell/test-deps:$tag"

        # Set variables for later jobs to use
        Import-Module ./PowerShell/tools/ci.psm1
        Set-BuildVariable -Name containerName -Value $containerName -IsOutput
        Set-BuildVariable -Name containerBuildName -Value $selectedImage.JobName -IsOutput
      name: getContainerTask
      displayName: Get Container
      continueOnError: true

  - template: templates/test/nix-container-test.yml
    parameters:
      name: container
      pool: ubuntu-20.04
      purpose: UnelevatedPesterTests
      tagSet: CI

  - template: templates/test/nix-container-test.yml
    parameters:
      name: container
      pool: ubuntu-20.04
      purpose: ElevatedPesterTests
      tagSet: CI

  - template: templates/test/nix-container-test.yml
    parameters:
      name: container
      pool: ubuntu-20.04
      purpose: UnelevatedPesterTests
      tagSet: Others

  - template: templates/test/nix-container-test.yml
    parameters:
      name: container
      pool: ubuntu-20.04
      purpose: ElevatedPesterTests
      tagSet: Others

- stage: PackageLinux
  displayName: Package Linux
  dependsOn: ["BuildLinuxStage"]
  jobs:
  - template: linux/templates/packaging.yml
    parameters:
      pool: ubuntu-20.04
