name: PR-$(System.PullRequest.PullRequestNumber)-$(Date:yyyyMMdd)$(Rev:.rr)
trigger:
  # Batch merge builds together while a merge build is running
  batch: true
  branches:
    include:
    - master
    - release*
  paths:
    exclude:
    - /src/*

pr:
  branches:
    include:
    - master
    - release*
  paths:
    exclude:
    - /src/*

resources:
- repo: self
  clean: true
phases:
- phase: Linux_CI

  queue:
    name: Hosted Ubuntu 1604
  steps:
  - powershell: |
      Get-ChildItem -Path env:
    displayName: Capture environment
    condition: succeededOrFailed()

  - powershell: |
      Install-Module -Name pester -Scope CurrentUser -Force
      Install-Module -Name ThreadJob -Scope CurrentUser -Force
    displayName: Install Dependencies
    condition: succeededOrFailed()
  - bash: |
      sudo npm install -g markdown-spellcheck@0.11.0
      find . -name \*.md -exec mdspell --report --en-us --ignore-numbers --ignore-acronyms {} \;

  - powershell:  Write-Host "##vso[build.updatebuildnumber]$env:BUILD_SOURCEBRANCHNAME-$env:BUILD_SOURCEVERSION-$((get-date).ToString("yyyyMMddhhmmss"))"
    displayName: Set Build Name for Non-PR
    condition: ne(variables['Build.Reason'], 'PullRequest')

  # Sometimes this folder is left behind with root permissions and causes many problems
  - bash: |
      sudo rm -rf ~/.npm/_cacache
    displayName: Remove Old NPM Caches
    condition: succeededOrFailed()

  - powershell: |
      Import-module ./build.psm1
      $path = Join-Path -Path $pwd -ChildPath './commonTestResults.xml'
      $results = invoke-pester -Script ./test/common -OutputFile $path -OutputFormat NUnitXml -PassThru
      Write-Host "##vso[results.publish type=NUnit;mergeResults=true;runTitle=Common Tests;publishRunAttachments=true;resultFiles=$path;]"
      if($results.TotalCount -eq 0 -or $results.FailedCount -gt 0)
      {
        throw "Markdown tests failed"
      }
    displayName: Run Common Tests
    condition: succeededOrFailed()
