name: PR-$(System.PullRequest.PullRequestNumber)-$(Date:yyyyMMdd)$(Rev:.rr)
trigger:
  # Batch merge builds together while a merge build is running
  batch: true
  branches:
    include:
    - master
    - release*
    - feature*

pr:
  branches:
    include:
    - master
    - release*
    - feature*

resources:
  repositories:
  - repository: ComplianceRepo
    type: github
    endpoint: PowerShell
    name: PowerShell/compliance
    ref: master

variables:
  - name: repoFolder
    value: PowerShell

jobs:
- job: CI_Compliance
  displayName: CI Compliance

  pool:
    vmImage: windows-latest

  variables:
    - name: repoPath
      value: $(Agent.BuildDirectory)\$(repoFolder)

  steps:
  - checkout: self
    clean: true
    path: $(repoFolder)

  - checkout: ComplianceRepo

    - template: ci-compliance.yml@ComplianceRepo
