name: UnifiedPackageBuild-$(Build.BuildId)
trigger:
  branches:
    include:
    - master
    - release*
pr:
  branches:
    include:
    - master
    - release*

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1

# Set AzDevOps Agent to clean the machine after the end of the build
resources:
- repo: self
  clean: true

jobs:
- template: templates/linux.yml
  parameters:
    buildName: deb
    pool: Hosted Ubuntu 1604

- template: templates/linux.yml
  parameters:
    buildName: rpm
    pool: Hosted Ubuntu 1604

- template: templates/linux.yml
  parameters:
    buildName: fxdependent
    pool: Hosted Ubuntu 1604

- template: templates/linux.yml
  parameters:
    buildName: alpine
    pool: Hosted Ubuntu 1604

- template: templates/mac.yml
