parameters:
  - name: "repoRoot"
    default: $(REPOROOT)

steps:
- pwsh: |
      $configPath = "${env:NugetConfigDir}/nuget.config"
      Import-Module ${{ parameters.repoRoot }}/build.psm1 -Force
      New-NugetConfigFile -NugetFeedUrl $(AzDevOpsFeed) -UserName $(AzDevOpsFeedUserName) -ClearTextPAT $(AzDevOpsFeedPAT2) -FeedName AzDevOpsFeed -Destination "${env:NugetConfigDir}"

      if(-not (Test-Path $configPath))
      {
          throw "nuget.config is not created"
      }
      Get-Content $configPath | Write-Verbose -Verbose
  displayName: 'Add nuget.config for Azure DevOps feed for PSGallery modules'
  condition: and(succeededOrFailed(), ne(variables['AzDevOpsFeed'], ''))
  env:
    NugetConfigDir: ${{ parameters.repoRoot }}/src/Modules

- pwsh: |
      $configPath = "${env:NugetConfigDir}/nuget.config"
      Import-Module ${{ parameters.repoRoot }}/build.psm1 -Force
      New-NugetConfigFile -NugetFeedUrl $(PSInternalNugetFeed) -UserName $(PSInternalNugetFeedUserName) -ClearTextPAT $(PSInternalNugetFeedPAT) -FeedName AzDevOpsFeed -Destination "${env:NugetConfigDir}"

      if(-not (Test-Path $configPath))
      {
          throw "nuget.config is not created"
      }
      Get-Content $configPath | Write-Verbose -Verbose
  displayName: 'Add nuget.config for Azure DevOps feed for packages'
  condition: and(succeededOrFailed(), ne(variables['PSInternalNugetFeed'], ''))
  env:
    NugetConfigDir: ${{ parameters.repoRoot }}

- pwsh: |
    # delete unused nuget.config files
    git rm test/perf/nuget.config
    git rm docs/host-powershell/sample/NuGet.config
    git rm test/hosting/NuGet.Config
    git rm test/tools/Modules/nuget.config
    git rm test/tools/NamedPipeConnection/nuget.config
    
    # commit the changes - this is a temporary workaround until we can get the 1ES team to fix the tooling
    git add -A
    git commit -m "commit nuget.config for Azure DevOps feed"
  displayName: 'Commit nuget changes'
  condition: and(succeededOrFailed(), ne(variables['PSInternalNugetFeed'], ''))
  workingDirectory: ${{ parameters.repoRoot }}

- task: nuget-security-analysis@0
  displayName: 'Run Secure Supply Chain analysis'
  condition: and(succeededOrFailed(), ne(variables['PSInternalNugetFeed'], ''), ne(variables['AzDevOpsFeed'], ''))
