# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.
# Please make sure to check all the converted content, it is your team's responsibility to make sure that the pipeline is still valid and functions as expected.
parameters:
  parentJobs: []
jobs:
- job: json
  variables:
  - name: runCodesignValidationInjection
    value: false
  - name: NugetSecurityAnalysisWarningLevel
    value: none
  - name: ob_outputDirectory
    value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'
  - group: AzureBlobServiceConnection
  displayName: Create Json for Blob
  dependsOn: ${{ parameters.parentJobs }}
  condition: succeeded()
  pool:
    type: windows
  steps:
  - checkout: self
    clean: true
  - template: /.pipelines/templates/SetVersionVariables.yml@self
    parameters:
      ReleaseTagVar: $(ReleaseTagVar)
      CreateJson: yes
  - task: AzureFileCopy@4
    displayName: 'upload daily-build-info JSON file to Azure - ${{ parameters.architecture }}'
    inputs:
      SourcePath: '$(BuildInfoPath)'
      azureSubscription: az-blob-cicd-infra
      Destination: AzureBlob
      storage: '$(StorageAccount)'
      ContainerName: 'BuildInfo'
    condition: and(succeeded(), eq(variables['IS_DAILY'], 'true'))
  - task: AzureCLI@1
    displayName: 'Make blob public'
    inputs:
      azureSubscription: az-blob-cicd-infra
      scriptLocation: inlineScript
      inlineScript: 'az storage container set-permission --account-name $(StorageAccount) --name $(azureVersion) --public-access blob'
    condition: and(succeeded(), eq(variables['IS_DAILY'], 'true'))
  - template: /.pipelines/templates/step/finalize.yml@self
