[0KRunning with gitlab-runner 16.6.0~beta.105.gd2263193 (d2263193)[0;m
[0K  on blue-4.saas-linux-small-amd64.runners-manager.gitlab.com/default J2nyww-s, system ID: s_cf1798852952[0;m
[0K  feature flags: FF_USE_IMPROVED_URL_MASKING:true[0;m
section_start:1709169186:resolve_secrets
[0K[0K[36;1mResolving secrets[0;m[0;m
section_end:1709169186:resolve_secrets
[0Ksection_start:1709169186:prepare_executor
[0K[0K[36;1mPreparing the "docker+machine" executor[0;m[0;m
[0KUsing Docker executor with image ruby:3.1 ...[0;m
[0KPulling docker image ruby:3.1 ...[0;m
[0KUsing docker image sha256:fe5345016b77964fe21e462507d7c6db1982a4f91d1f85ebf0b2babcfe915a04 for ruby:3.1 with digest ruby@sha256:3c24464780a402a8b9ad6215848a025bb79eec4c822803434944ddc1dbe3f2bc ...[0;m
section_end:1709169204:prepare_executor
[0Ksection_start:1709169204:prepare_script
[0K[0K[36;1mPreparing environment[0;m[0;m
Running on runner-j2nyww-s-project-55059759-concurrent-0 via runner-j2nyww-s-s-l-s-amd64-1709169073-f36c89a5...
section_end:1709169209:prepare_script
[0Ksection_start:1709169209:get_sources
[0K[0K[36;1mGetting source from Git repository[0;m[0;m
[32;1mFetching changes with git depth set to 20...[0;m
Initialized empty Git repository in /builds/helpbug/PowerShell/.git/
[32;1mCreated fresh repository.[0;m
[32;1mChecking out 760b31a1 as detached HEAD (ref is set-dependency-scanning-config-1)...[0;m

[32;1mSkipping Git submodules setup[0;m
[32;1m$ git remote set-url origin "${CI_REPOSITORY_URL}"[0;m
section_end:1709169212:get_sources
[0Ksection_start:1709169212:step_script
[0K[0K[36;1mExecuting "step_script" stage of the job script[0;m[0;m
[0KUsing docker image sha256:fe5345016b77964fe21e462507d7c6db1982a4f91d1f85ebf0b2babcfe915a04 for ruby:3.1 with digest ruby@sha256:3c24464780a402a8b9ad6215848a025bb79eec4c822803434944ddc1dbe3f2bc ...[0;m
[32;1m$ echo "Deploying application..."[0;m
Deploying application...
[32;1m$ echo "Application successfully deployed."[0;m
Application successfully deployed.
section_end:1709169213:step_script
[0Ksection_start:1709169213:cleanup_file_variables
[0K[0K[36;1mCleaning up project directory and file based variables[0;m[0;m
section_end:1709169213:cleanup_file_variables
[0K[32;1mJob succeeded[0;m
