# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

name: Update cgmanifest
on:
    workflow_dispatch:
    schedule:
    # At 13:00 UTC every day.
    - cron:  '0 13 * * *'
    pull_request:
      branches:
      - master

defaults:
  run:
    shell: pwsh

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1
  CGMANIFEST_PATH: ''

jobs:
  update-cgmanifest:
    name: Update cgmanifest
    timeout-minutes: 15
    runs-on: windows-latest
    if: github.repository == 'PowerShell/PowerShell'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache DotNet
        uses: actions/cache@v2
        with:
          path: |
            ~\AppData\Local\Microsoft\dotnet
          key: ${{ runner.os }}-${{ hashFiles('**/DotnetRuntimeMetadata.json') }}
      - name: Sync tags
        run: |
          git fetch --prune --unshallow --tags
      - name: Install Ships provider to deal with project.assets.json
        run: |
          Install-Module -Name dotnet.project.assets -force
      - name: Bootstrap
        run: |
          Import-Module ./build.psm1
          Start-PSBootStrap
      - name: (PR) Verify cgmanifest is up to date
        if: github.event_name == 'pull_request'
        run: |
          Import-Module ./build.psm1
          Find-Dotnet
          ./tools/findMissingNotices.ps1
      - name: (Scheduled) Update Notices file
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: |
          Invoke-WebRequest -Uri https://aka.ms/pwsh-daily-tpn -OutFile ./ThirdPartyNotices.txt
      - name: (Scheduled) Update cgmanifest
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: |
          Import-Module ./build.psm1
          Find-Dotnet
          ./tools/findMissingNotices.ps1 -Fix
      - uses: actions/upload-artifact@v2
        if: env.CGMANIFEST_PATH != ''
        with:
          name: cgmanifest
          path: ${{ env.CGMANIFEST_PATH }}
      - name: (Scheduled) Create Pull Request
        uses: peter-evans/create-pull-request@v3
        id: cpr
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        with:
          commit-message: "Update to the latest license and the cgmanifest with missing or updated components"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: "Update to the latest license and the cgmanifest with missing or updated components"
          reviewers: travisez13
          base: master
          draft: false
          branch: update-cgmanifest
